// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['handler']['Handler']['Close']();
}

export function CreatePod(arg1) {
  return window['go']['handler']['Handler']['CreatePod'](arg1);
}

export function DeletePod(arg1) {
  return window['go']['handler']['Handler']['DeletePod'](arg1);
}

export function Fork(arg1, arg2) {
  return window['go']['handler']['Handler']['Fork'](arg1, arg2);
}

export function ForkFromReference(arg1, arg2) {
  return window['go']['handler']['Handler']['ForkFromReference'](arg1, arg2);
}

export function GetCashedPods() {
  return window['go']['handler']['Handler']['GetCashedPods']();
}

export function GetPodsList() {
  return window['go']['handler']['Handler']['GetPodsList']();
}

export function Load(arg1, arg2, arg3) {
  return window['go']['handler']['Handler']['Load'](arg1, arg2, arg3);
}

export function Login(arg1, arg2) {
  return window['go']['handler']['Handler']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['handler']['Handler']['Logout']();
}

export function Mount(arg1, arg2, arg3) {
  return window['go']['handler']['Handler']['Mount'](arg1, arg2, arg3);
}

export function MountSubscribedPod(arg1, arg2, arg3) {
  return window['go']['handler']['Handler']['MountSubscribedPod'](arg1, arg2, arg3);
}

export function ReceivePod(arg1, arg2) {
  return window['go']['handler']['Handler']['ReceivePod'](arg1, arg2);
}

export function SharePod(arg1) {
  return window['go']['handler']['Handler']['SharePod'](arg1);
}

export function Start(arg1) {
  return window['go']['handler']['Handler']['Start'](arg1);
}

export function StartCacheCleaner(arg1) {
  return window['go']['handler']['Handler']['StartCacheCleaner'](arg1);
}

export function SubscribedPods() {
  return window['go']['handler']['Handler']['SubscribedPods']();
}

export function Sync(arg1) {
  return window['go']['handler']['Handler']['Sync'](arg1);
}

export function Unmount(arg1) {
  return window['go']['handler']['Handler']['Unmount'](arg1);
}

export function UnmountSubscribedPod(arg1) {
  return window['go']['handler']['Handler']['UnmountSubscribedPod'](arg1);
}
