// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<void>;

export function CreatePod(arg1:string):Promise<any>;

export function DeletePod(arg1:string):Promise<void>;

export function Fork(arg1:string,arg2:string):Promise<void>;

export function ForkFromReference(arg1:string,arg2:string):Promise<void>;

export function GetCashedPods():Promise<any>;

export function GetPodsList():Promise<Array<any>>;

export function Load(arg1:string,arg2:string,arg3:string):Promise<any>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Mount(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function MountSubscribedPod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReceivePod(arg1:string,arg2:string):Promise<void>;

export function SharePod(arg1:string):Promise<string>;

export function Start(arg1:any):Promise<void>;

export function StartCacheCleaner(arg1:context.Context):Promise<void>;

export function SubscribedPods():Promise<Array<any>>;

export function Sync(arg1:string):Promise<void>;

export function Unmount(arg1:string):Promise<void>;

export function UnmountSubscribedPod(arg1:string):Promise<void>;
