// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['handler']['Handler']['Close']();
}

export function CreatePod(arg1) {
  return window['go']['handler']['Handler']['CreatePod'](arg1);
}

export function GetCashedPods() {
  return window['go']['handler']['Handler']['GetCashedPods']();
}

export function GetPodsList() {
  return window['go']['handler']['Handler']['GetPodsList']();
}

export function Load(arg1, arg2, arg3) {
  return window['go']['handler']['Handler']['Load'](arg1, arg2, arg3);
}

export function Login(arg1, arg2) {
  return window['go']['handler']['Handler']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['handler']['Handler']['Logout']();
}

export function Mount(arg1, arg2, arg3) {
  return window['go']['handler']['Handler']['Mount'](arg1, arg2, arg3);
}

export function Start(arg1) {
  return window['go']['handler']['Handler']['Start'](arg1);
}

export function Unmount(arg1) {
  return window['go']['handler']['Handler']['Unmount'](arg1);
}
