// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForgetPassword() {
  return window['go']['main']['Account']['ForgetPassword']();
}

export function Get() {
  return window['go']['main']['Account']['Get']();
}

export function HasRemembered() {
  return window['go']['main']['Account']['HasRemembered']();
}

export function RememberPassword(arg1, arg2) {
  return window['go']['main']['Account']['RememberPassword'](arg1, arg2);
}
