// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['handler']['Handler']['Close']();
}

export function GetPodsList(arg1) {
  return window['go']['handler']['Handler']['GetPodsList'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['handler']['Handler']['Login'](arg1, arg2);
}

export function Mount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['handler']['Handler']['Mount'](arg1, arg2, arg3, arg4, arg5);
}

export function Start(arg1) {
  return window['go']['handler']['Handler']['Start'](arg1);
}

export function Unmount(arg1, arg2) {
  return window['go']['handler']['Handler']['Unmount'](arg1, arg2);
}
