// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildTime() {
  return window['go']['main']['about']['BuildTime']();
}

export function Version() {
  return window['go']['main']['about']['Version']();
}
