// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForgetPassword():Promise<void>;

export function Get():Promise<any>;

export function HasRemembered():Promise<boolean>;

export function RememberPassword(arg1:string,arg2:string):Promise<void>;
