// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ForgetPassword():Promise<void>;

export function Get():Promise<main.Account>;

export function HasRemembered():Promise<boolean>;

export function RememberPassword(arg1:string,arg2:string):Promise<void>;
