// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';

export function GetConfig():Promise<api.FairOSConfig>;

export function GetMountPoint():Promise<string>;

export function IsSet():Promise<boolean>;

export function ReadConfig():Promise<Error>;

export function SetupConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<Error>;
