// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoMount() {
  return window['go']['main']['conf']['GetAutoMount']();
}

export function GetConfig() {
  return window['go']['main']['conf']['GetConfig']();
}

export function GetMountPoint() {
  return window['go']['main']['conf']['GetMountPoint']();
}

export function GetMountedPods() {
  return window['go']['main']['conf']['GetMountedPods']();
}

export function IsSet() {
  return window['go']['main']['conf']['IsSet']();
}

export function ReadConfig() {
  return window['go']['main']['conf']['ReadConfig']();
}

export function SetupConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['conf']['SetupConfig'](arg1, arg2, arg3, arg4, arg5);
}
